const AllBackgroundElements = [
  // Unique
  {
    id: 0,
    name: "Arcade",
    variant: "Default",
    weight: 5,
    path: "Background/ARCADE.PNG",
    layerIndex: 0,
  },
  {
    id: 1,
    name: "Day",
    variant: "Default",
    weight: 60,
    path: "Background/DAY.PNG",
    layerIndex: 0,
  },
  {
    id: 2,
    name: "Night",
    variant: "Default",
    weight: 60,
    path: "Background/NIGHT.JPG",
    layerIndex: 0,
  },
  {
    id: 3,
    name: "New City",
    variant: "Default",
    weight: 35,
    path: "Background/NEW CITY.JPG",
    layerIndex: 0,
  },
  {
    id: 4,
    name: "School",
    variant: "Default",
    weight: 22,
    path: "Background/SCHOOL.JPG",
    layerIndex: 0,
  },
  {
    id: 5,
    name: "Palm",
    variant: "Default",
    weight: 81,
    path: "Background/PALM.PNG",
    layerIndex: 0,
  },
  // Simple
  {
    id: 6,
    name: "Grey",
    variant: "Default",
    weight: 100,
    path: "Background/GREY.PNG",
    layerIndex: 0,
  },
  {
    id: 7,
    name: "Pink",
    variant: "Default",
    weight: 100,
    path: "Background/PINK.PNG",
    layerIndex: 0,
  },
  {
    id: 8,
    name: "Green",
    variant: "Default",
    weight: 100,
    path: "Background/GREEN.PNG",
    layerIndex: 0,
  },
  {
    id: 9,
    name: "Peach",
    variant: "Default",
    weight: 100,
    path: "Background/PEACH.PNG",
    layerIndex: 0,
  },
  {
    id: 10,
    name: "Blue",
    variant: "Default",
    weight: 100,
    path: "Background/BLUE.PNG",
    layerIndex: 0,
  },
  // Textured
  {
    id: 11,
    name: "Textured Green",
    variant: "Default",
    weight: 100,
    path: "Background/TEXTURE GREEN.PNG",
    layerIndex: 0,
  },
  {
    id: 12,
    name: "Texture Grey",
    variant: "Default",
    weight: 100,
    path: "Background/TEXTURE GREY.PNG",
    layerIndex: 0,
  },
  {
    id: 13,
    name: "Textured Pink",
    variant: "Default",
    weight: 100,
    path: "Background/TEXTURE PINK.PNG",
    layerIndex: 0,
  },
  {
    id: 14,
    name: "Textured Dark Grey",
    variant: "Default",
    weight: 100,
    path: "Background/TEXTURE DARK GREY.PNG",
    layerIndex: 0,
  },
];
const AllBaseElements = [
  // GURS, Off SHOULDER, JEANS JACKET, JEANS PINK + BOMBER, RED JEANS, SCARFACE SUIT, SHIRT, TSHIRT, JEANS WHITE
  {
    id: 0,
    name: "Mocha",
    variant: "GURS",
    weight: 389,
    path: "variants/GURS/Base/MOCHA.PNG",
    layerIndex: 1,
  },
  {
    id: 1,
    name: "Olive",
    variant: "GURS",
    weight: 387,
    path: "variants/GURS/Base/OLIVE.PNG",
    layerIndex: 1,
  },
  {
    id: 2,
    name: "Light",
    variant: "GURS",
    weight: 387,
    path: "variants/GURS/Base/LIGHT.PNG",
    layerIndex: 1,
  },
  {
    id: 0,
    name: "Mocha",
    variant: "OFF SHOULDER",
    weight: 389,
    path: "variants/OFF SHOULDER/Base/MOCHA.PNG",
    layerIndex: 1,
  },
  {
    id: 1,
    name: "Olive",
    variant: "OFF SHOULDER",
    weight: 387,
    path: "variants/OFF SHOULDER/Base/OLIVE.PNG",
    layerIndex: 1,
  },
  {
    id: 2,
    name: "Light",
    variant: "OFF SHOULDER",
    weight: 387,
    path: "variants/OFF SHOULDER/Base/LIGHT.PNG",
    layerIndex: 1,
  },
  {
    id: 0,
    name: "Mocha",
    variant: "JEANS JACKET",
    weight: 389,
    path: "variants/JEANS JACKET/Base/MOCHA.PNG",
    layerIndex: 1,
  },
  {
    id: 1,
    name: "Olive",
    variant: "JEANS JACKET",
    weight: 387,
    path: "variants/JEANS JACKET/Base/OLIVE.PNG",
    layerIndex: 1,
  },
  {
    id: 2,
    name: "Light",
    variant: "JEANS JACKET",
    weight: 387,
    path: "variants/JEANS JACKET/Base/LIGHT.PNG",
    layerIndex: 1,
  },
  {
    id: 0,
    name: "Mocha",
    variant: "JEANS PINK + BOMBER",
    weight: 389,
    path: "variants/JEANS PINK + BOMBER/Base/MOCHA.PNG",
    layerIndex: 1,
  },
  {
    id: 1,
    name: "Olive",
    variant: "JEANS PINK + BOMBER",
    weight: 387,
    path: "variants/JEANS PINK + BOMBER/Base/OLIVE.PNG",
    layerIndex: 1,
  },
  {
    id: 2,
    name: "Light",
    variant: "JEANS PINK + BOMBER",
    weight: 387,
    path: "variants/JEANS PINK + BOMBER/Base/LIGHT.PNG",
    layerIndex: 1,
  },
  {
    id: 0,
    name: "Mocha",
    variant: "RED JEANS",
    weight: 389,
    path: "variants/RED JEANS/Base/MOCHA.PNG",
    layerIndex: 1,
  },
  {
    id: 1,
    name: "Olive",
    variant: "RED JEANS",
    weight: 387,
    path: "variants/RED JEANS/Base/OLIVE.PNG",
    layerIndex: 1,
  },
  {
    id: 2,
    name: "Light",
    variant: "RED JEANS",
    weight: 387,
    path: "variants/RED JEANS/Base/LIGHT.PNG",
    layerIndex: 1,
  },
  {
    id: 0,
    name: "Mocha",
    variant: "SCARFACE SUIT",
    weight: 389,
    path: "variants/SCARFACE SUIT/Base/MOCHA.PNG",
    layerIndex: 1,
  },
  {
    id: 1,
    name: "Olive",
    variant: "SCARFACE SUIT",
    weight: 387,
    path: "variants/SCARFACE SUIT/Base/OLIVE.PNG",
    layerIndex: 1,
  },
  {
    id: 2,
    name: "Light",
    variant: "SCARFACE SUIT",
    weight: 387,
    path: "variants/SCARFACE SUIT/Base/LIGHT.PNG",
    layerIndex: 1,
  },
  {
    id: 0,
    name: "Mocha",
    variant: "SHIRT",
    weight: 389,
    path: "variants/SHIRT/Base/MOCHA.PNG",
    layerIndex: 1,
  },
  {
    id: 1,
    name: "Olive",
    variant: "SHIRT",
    weight: 387,
    path: "variants/SHIRT/Base/OLIVE.PNG",
    layerIndex: 1,
  },
  {
    id: 2,
    name: "Light",
    variant: "SHIRT",
    weight: 387,
    path: "variants/SHIRT/Base/LIGHT.PNG",
    layerIndex: 1,
  },
  {
    id: 0,
    name: "Mocha",
    variant: "TSHIRTS",
    weight: 389,
    path: "variants/TSHIRTS/Base/MOCHA.PNG",
    layerIndex: 1,
  },
  {
    id: 1,
    name: "Olive",
    variant: "TSHIRTS",
    weight: 387,
    path: "variants/TSHIRTS/Base/OLIVE.PNG",
    layerIndex: 1,
  },
  {
    id: 2,
    name: "Light",
    variant: "TSHIRTS",
    weight: 387,
    path: "variants/TSHIRTS/Base/LIGHT.PNG",
    layerIndex: 1,
  },
  {
    id: 0,
    name: "Mocha",
    variant: "JEANS WHITE",
    weight: 389,
    path: "variants/JEANS WHITE/Base/MOCHA.PNG",
    layerIndex: 1,
  },
  {
    id: 1,
    name: "Olive",
    variant: "JEANS WHITE",
    weight: 387,
    path: "variants/JEANS WHITE/Base/OLIVE.PNG",
    layerIndex: 1,
  },
  {
    id: 2,
    name: "Light",
    variant: "JEANS WHITE",
    weight: 387,
    path: "variants/JEANS WHITE/Base/LIGHT.PNG",
    layerIndex: 1,
  },
];
const AllClothesElements = [
  //VARIANTs:  GURS, Off SHOULDER, JEANS JACKET, JEANS PINK + BOMBER, RED JEANS, SCARFACE SUIT, SHIRT, TSHIRT, JEANS WHITE
  {
    id: 0,
    name: "69 Bomber",
    variant: "GURS",
    weight: 5,
    path: "variants/GURS/Clothes/69 BOMBER.PNG",
    layerIndex: 2,
  },
  {
    id: 1,
    name: "80's Zipped Bomber",
    variant: "GURS",
    weight: 30,
    path: "variants/GURS/Clothes/80 ZIPPED BOMBER.PNG",
    layerIndex: 2,
  },
  {
    id: 2,
    name: "80's Hoodie",
    variant: "GURS",
    weight: 15,
    path: "variants/GURS/Clothes/80 HOODIE.PNG",
    layerIndex: 2,
  },
  {
    id: 3,
    name: "Pink Azelia Bomber",
    variant: "GURS",
    weight: 30,
    path: "variants/GURS/Clothes/AZELIA BOMBER PINK.PNG",
    layerIndex: 2,
  },
  {
    id: 4,
    name: "Red Azelia Bomber",
    variant: "GURS",
    weight: 30,
    path: "variants/GURS/Clothes/AZELIA BOMBER RED.PNG",
    layerIndex: 2,
  },
  {
    id: 5,
    name: "Backpack",
    variant: "GURS",
    weight: 10,
    path: "variants/GURS/Clothes/BACKPACK.PNG",
    layerIndex: 2,
  },
  {
    id: 6,
    name: "Arena Bomber",
    variant: "GURS",
    weight: 25,
    path: "variants/GURS/Clothes/BOMBER ARENA.PNG",
    layerIndex: 2,
  },
  {
    id: 7,
    name: "Baby COQ Bomber",
    variant: "GURS",
    weight: 30,
    path: "variants/GURS/Clothes/BOMBER BABY COQ.PNG",
    layerIndex: 2,
  },
  {
    id: 8,
    name: "Baby GURS Bomber",
    variant: "GURS",
    weight: 30,
    path: "variants/GURS/Clothes/BOMBER BABY GURS.PNG",
    layerIndex: 2,
  },
  {
    id: 9,
    name: "Baby OG Bomber",
    variant: "GURS",
    weight: 30,
    path: "variants/GURS/Clothes/BOMBER BABY OG.PNG",
    layerIndex: 2,
  },
  {
    id: 10,
    name: "Baby NOCHILL Bomber",
    variant: "GURS",
    weight: 30,
    path: "variants/GURS/Clothes/BOMBER BABY NOCHILL.PNG",
    layerIndex: 2,
  },
  {
    id: 11,
    name: "Bitcoin Bomber",
    variant: "GURS",
    weight: 10,
    path: "variants/GURS/Clothes/BOMBER BITCOIN.PNG",
    layerIndex: 2,
  },
  {
    id: 12,
    name: "COQ Bomber",
    variant: "GURS",
    weight: 10,
    path: "variants/GURS/Clothes/BOMBER COQ.PNG",
    layerIndex: 2,
  },
  {
    id: 13,
    name: "GURS Bomber",
    variant: "GURS",
    weight: 10,
    path: "variants/GURS/Clothes/BOMBER GURS.PNG",
    layerIndex: 2,
  },
  {
    id: 14,
    name: "NOCHILL Bomber",
    variant: "GURS",
    weight: 10,
    path: "variants/GURS/Clothes/BOMBER NOCHILL.PNG",
    layerIndex: 2,
  },
  {
    id: 15,
    name: "OG Bomber",
    variant: "GURS",
    weight: 10,
    path: "variants/GURS/Clothes/BOMBER OG.PNG",
    layerIndex: 2,
  },
  {
    id: 16,
    name: "Pepa Bomber",
    variant: "GURS",
    weight: 10,
    path: "variants/GURS/Clothes/BOMBER PEPA.PNG",
    layerIndex: 2,
  },
  {
    id: 17,
    name: "Gold Bomber",
    variant: "GURS",
    weight: 7,
    path: "variants/GURS/Clothes/GOLD BOMBER.PNG",
    layerIndex: 2,
  },
  {
    id: 18,
    name: "GURS Power",
    variant: "GURS",
    weight: 30,
    path: "variants/GURS/Clothes/GURS POWER.PNG",
    layerIndex: 2,
  },
  {
    id: 19,
    name: "Scarface Black Hoodie",
    variant: "GURS",
    weight: 3,
    path: "variants/GURS/Clothes/SCARFACE HOODIE BLACK.PNG",
    layerIndex: 2,
  },
  {
    id: 20,
    name: "Scarface White Hoodie",
    variant: "GURS",
    weight: 3,
    path: "variants/GURS/Clothes/SCARFACE HOODIE WHITE.PNG",
    layerIndex: 2,
  },
  {
    id: 21,
    name: "Blue Striped Suit",
    variant: "GURS",
    weight: 20,
    path: "variants/GURS/Clothes/STRIPE SUIT BLUE.PNG",
    layerIndex: 2,
  },
  {
    id: 22,
    name: "Pink Striped Suit",
    variant: "GURS",
    weight: 20,
    path: "variants/GURS/Clothes/STRIPE SUIT PINK.PNG",
    layerIndex: 2,
  },
  {
    id: 23,
    name: "Sweater",
    variant: "GURS",
    weight: 20,
    path: "variants/GURS/Clothes/Sweater.PNG",
    layerIndex: 2,
  },
  {
    id: 24,
    name: "White Player Sweater",
    variant: "GURS",
    weight: 5,
    path: "variants/GURS/Clothes/WHITE PLAYER.PNG",
    layerIndex: 2,
  },
  {
    id: 25,
    name: "Off the Shoulder",
    variant: "OFF SHOULDER",
    weight: 30,
    path: "variants/OFF SHOULDER/Clothes/GURS OFF SHOULDER.PNG",
    layerIndex: 2,
  },
  {
    id: 26,
    name: "Blue Jeans Jacket",
    variant: "JEANS JACKET",
    weight: 10,
    path: "variants/JEANS JACKET/Clothes/JEANS JACKET BLUE.PNG",
    layerIndex: 2,
  },
  {
    id: 27,
    name: "Pink Jeans Jacket",
    variant: "JEANS JACKET",
    weight: 10,
    path: "variants/JEANS JACKET/Clothes/JEANS JACKET PINK.PNG",
    layerIndex: 2,
  },
  {
    id: 28,
    name: "Grey Jeans Jacket",
    variant: "JEANS JACKET",
    weight: 10,
    path: "variants/JEANS JACKET/Clothes/JEANS JACKET GREY.PNG",
    layerIndex: 2,
  },
  {
    id: 29,
    name: "Pink Jeans Cutoff",
    variant: "JEANS PINK + BOMBER",
    weight: 30,
    path: "variants/JEANS PINK + BOMBER/Clothes/JEANS PINK.PNG",
    layerIndex: 2,
  },
  {
    id: 30,
    name: "Red Carrot Bomber",
    variant: "JEANS PINK + BOMBER",
    weight: 60,
    path: "variants/JEANS PINK + BOMBER/Clothes/RED CAROT.PNG",
    layerIndex: 2,
  },
  {
    id: 31,
    name: "Red with Overalls",
    variant: "RED JEANS",
    weight: 20,
    path: "variants/RED JEANS/Clothes/RED JEANS.PNG",
    layerIndex: 2,
  },
  {
    id: 32,
    name: "Scarface Suit",
    variant: "SCARFACE SUIT",
    weight: 3,
    path: "variants/SCARFACE SUIT/Clothes/SCARFACE SUIT.PNG",
    layerIndex: 2,
  },
  {
    id: 33,
    name: "Blue Collar Shirt",
    variant: "SHIRT",
    weight: 50,
    path: "variants/SHIRT/Clothes/BLUE COLLAR SHIRT.PNG",
    layerIndex: 2,
  },
  {
    id: 34,
    name: "Pink Collar Shirt",
    variant: "SHIRT",
    weight: 50,
    path: "variants/SHIRT/Clothes/PINK COLLAR SHIRT.PNG",
    layerIndex: 2,
  },
  {
    id: 35,
    name: "Blue Jeans Jumpsuit",
    variant: "TSHIRTS",
    weight: 33,
    path: "variants/TSHIRTS/Clothes/JEANS JUMPSUIT BLUE.PNG",
    layerIndex: 2,
  },
  {
    id: 36,
    name: "Pink Jeans Jumpsuit",
    variant: "TSHIRTS",
    weight: 33,
    path: "variants/TSHIRTS/Clothes/JEANS JUMPSUIT PINK.PNG",
    layerIndex: 2,
  },
  {
    id: 37,
    name: "Grey Jeans Jumpsuit",
    variant: "TSHIRTS",
    weight: 33,
    path: "variants/TSHIRTS/Clothes/JEANS JUMPSUIT GREY.PNG",
    layerIndex: 2,
  },
  {
    id: 38,
    name: "Blue Sport Bomber",
    variant: "TSHIRTS",
    weight: 16,
    path: "variants/TSHIRTS/Clothes/SPORT SHORT BOMBER BLUE.PNG",
    layerIndex: 2,
  },
  {
    id: 39,
    name: "Pink Sport Bomber",
    variant: "TSHIRTS",
    weight: 16,
    path: "variants/TSHIRTS/Clothes/SPORT SHORT BOMBER PINK.PNG",
    layerIndex: 2,
  },
  {
    id: 40,
    name: "Purple Sport Bomber",
    variant: "TSHIRTS",
    weight: 16,
    path: "variants/TSHIRTS/Clothes/SPORT SHORT BOMBER PURPLE.PNG",
    layerIndex: 2,
  },
  {
    id: 41,
    name: "Arena T-Shirt",
    variant: "TSHIRTS",
    weight: 10,
    path: "variants/TSHIRTS/Clothes/TSHIRT ARENA.PNG",
    layerIndex: 2,
  },
  {
    id: 42,
    name: "Atari T-Shirt",
    variant: "TSHIRTS",
    weight: 20,
    path: "variants/TSHIRTS/Clothes/TSHIRT ATARI.PNG",
    layerIndex: 2,
  },
  {
    id: 43,
    name: "Car T-Shirt",
    variant: "TSHIRTS",
    weight: 20,
    path: "variants/TSHIRTS/Clothes/TSHIRT CAR.PNG",
    layerIndex: 2,
  },
  {
    id: 44,
    name: "GURS Trading T-Shirt",
    variant: "TSHIRTS",
    weight: 20,
    path: "variants/TSHIRTS/Clothes/TSHIRT GURS TRADE.PNG",
    layerIndex: 2,
  },
  {
    id: 45,
    name: "White GURS T-Shirt",
    variant: "TSHIRTS",
    weight: 125,
    path: "variants/TSHIRTS/Clothes/TSHIRT GURS WHITE.PNG",
    layerIndex: 2,
  },
  {
    id: 46,
    name: "GURS T-Shirt",
    variant: "TSHIRTS",
    weight: 20,
    path: "variants/TSHIRTS/Clothes/TSHIRT GURS.PNG",
    layerIndex: 2,
  },
  {
    id: 47,
    name: "Moon T-Shirt",
    variant: "TSHIRTS",
    weight: 20,
    path: "variants/TSHIRTS/Clothes/TSHIRT MOON.PNG",
    layerIndex: 2,
  },
  {
    id: 48,
    name: "Pepa T-Shirt",
    variant: "TSHIRTS",
    weight: 10,
    path: "variants/TSHIRTS/Clothes/TSHIRT PEPA.PNG",
    layerIndex: 2,
  },
  {
    id: 49,
    name: "SEGA T-Shirt",
    variant: "TSHIRTS",
    weight: 20,
    path: "variants/TSHIRTS/Clothes/TSHIRT SEGA.PNG",
    layerIndex: 2,
  },
  {
    id: 50,
    name: "Walkman T-Shirt",
    variant: "TSHIRTS",
    weight: 20,
    path: "variants/TSHIRTS/Clothes/TSHIRT WALKMAN.PNG",
    layerIndex: 2,
  },
  {
    id: 51,
    name: "White Jeans Bomber",
    variant: "JEANS WHITE",
    weight: 25,
    path: "variants/JEANS WHITE/Clothes/WHITE JEANS.PNG",
    layerIndex: 2,
  },
];

const AllEyeElements = [
  {
    id: 0,
    name: "Blue",
    variant: "Default",
    weight: 232,
    path: "Eyes/Blue Eyes.PNG",
    layerIndex: 3,
  },
  {
    id: 1,
    name: "Brown",
    variant: "Default",
    weight: 465,
    path: "Eyes/Brown Eyes.PNG",
    layerIndex: 3,
  },
  {
    id: 2,
    name: "Green",
    variant: "Default",
    weight: 232,
    path: "Eyes/Green Eyes.PNG",
    layerIndex: 3,
  },
  {
    id: 3,
    name: "Grey",
    variant: "Default",
    weight: 234,
    path: "Eyes/Grey Eyes.PNG",
    layerIndex: 3,
  },
];
const AllGlassesElements = [
  {
    id: 0,
    name: "Pink Chick",
    variant: "Default",
    weight: 5,
    path: "Glasses/PINK CHICK.PNG",
    layerIndex: 4,
  },
  {
    id: 1,
    name: "Pink",
    variant: "Default",
    weight: 5,
    path: "Glasses/PINK GLASS.PNG",
    layerIndex: 4,
  },
  {
    id: 2,
    name: "Polaroid Gold",
    variant: "Default",
    weight: 4,
    path: "Glasses/POLAROID GOLD.PNG",
    layerIndex: 4,
  },
  {
    id: 3,
    name: "Polaroid Pink",
    variant: "Default",
    weight: 4,
    path: "Glasses/POLAROID PINK.PNG",
    layerIndex: 4,
  }, //polaroid purple, red, white
  {
    id: 4,
    name: "Polaroid Purple",
    variant: "Default",
    weight: 4,
    path: "Glasses/POLAROID PURPLE.PNG",
    layerIndex: 4,
  },
  {
    id: 5,
    name: "Polaroid Red",
    variant: "Default",
    weight: 4,
    path: "Glasses/POLAROID RED.PNG",
    layerIndex: 4,
  },
  {
    id: 6,
    name: "Polaroid White",
    variant: "Default",
    weight: 4,
    path: "Glasses/POLAROID WHITE.PNG",
    layerIndex: 4,
  },
  {
    id: 7,
    name: "Pink Striped",
    variant: "Default",
    weight: 3,
    path: "Glasses/STRIPED GLASS.PNG",
  }, //yellow
  {
    id: 8,
    name: "Yellow",
    variant: "Default",
    weight: 5,
    path: "Glasses/YELLOW GLASS.PNG",
    layerIndex: 4,
  }, // none
  {
    id: 9,
    name: "None",
    variant: "Default",
    weight: 1125,
    path: "Glasses/NONE.PNG",
    layerIndex: 4,
  },
];
const AllHairElements = [
  {
    id: 0,
    name: "Blonde Ponytails",
    variant: "Default",
    weight: 5,
    path: "Hair/2 PONY TAILS BLONDE.PNG",
    layerIndex: 5,
  },
  {
    id: 1,
    name: "Light Brown Ponytails",
    variant: "Default",
    weight: 5,
    path: "Hair/2 PONY TAILS LIGHT BROWN.PNG",
    layerIndex: 5,
  },
  {
    id: 2,
    name: "Red Ponytails",
    variant: "Default",
    weight: 5,
    path: "Hair/2 PONY TAILS RED.PNG",
    layerIndex: 5,
  },
  {
    id: 3,
    name: "Blonde Long Curly",
    variant: "Default",
    weight: 85,
    path: "Hair/BLONDE LONG CURLY.PNG",
    layerIndex: 5,
  },
  {
    id: 4,
    name: "Breakfast Blonde",
    variant: "Default",
    weight: 20,
    path: "Hair/BREAKFAST BLONDE.PNG",
    layerIndex: 5,
  },
  {
    id: 5,
    name: "Breakfast Light Brown",
    variant: "Default",
    weight: 20,
    path: "Hair/BREAKFAST LIGHT BROWN.PNG",
    layerIndex: 5,
  },
  {
    id: 6,
    name: "Breakfast Brown",
    variant: "Default",
    weight: 20,
    path: "Hair/BREAKFAST BROWN.PNG",
    layerIndex: 5,
  },
  {
    id: 7,
    name: "Breakfast Light Red",
    variant: "Default",
    weight: 20,
    path: "Hair/BREAKFAST LIGHT RED.PNG",
    layerIndex: 5,
  },
  {
    id: 8,
    name: "Brown Long Curly",
    variant: "Default",
    weight: 85,
    path: "Hair/BROWN LONG CURLY.PNG",
    layerIndex: 5,
  },
  {
    id: 9,
    name: "Curly Bomb Brown",
    variant: "Default",
    weight: 40,
    path: "Hair/CURLY BOMB BROWN.PNG",
    layerIndex: 5,
  },
  {
    id: 10,
    name: "Curly Bomb Red",
    variant: "Default",
    weight: 40,
    path: "Hair/CURLY BOMB RED.PNG",
    layerIndex: 5,
  },
  {
    id: 11,
    name: "Curly Ponytail Blonde",
    variant: "Default",
    weight: 15,
    path: "Hair/CURLY PONY TAIL BLONDE.PNG",
    layerIndex: 5,
  },
  {
    id: 12,
    name: "Curly Ponytail Brown",
    variant: "Default",
    weight: 15,
    path: "Hair/CURLY PONY TAIL BROWN.PNG",
    layerIndex: 5,
  },
  {
    id: 13,
    name: "Curly Ponytail Red",
    variant: "Default",
    weight: 15,
    path: "Hair/CURLY PONY TAIL RED.PNG",
    layerIndex: 5,
  },
  {
    id: 14,
    name: "Dreamy Long Blonde",
    variant: "Default",
    weight: 20,
    path: "Hair/DREAMY LONG BLONDE.PNG",
    layerIndex: 5,
  },
  {
    id: 15,
    name: "Dreamy Long Brown",
    variant: "Default",
    weight: 20,
    path: "Hair/DREAMY LONG BROWN.PNG",
    layerIndex: 5,
  },
  {
    id: 16,
    name: "Dreamy Long Light Brown",
    variant: "Default",
    weight: 20,
    path: "Hair/DREAMY LONG LIGHT BROWN.PNG",
    layerIndex: 5,
  },
  {
    id: 17,
    name: "Dreamy Long Red",
    variant: "Default",
    weight: 20,
    path: "Hair/DREAMY LONG RED.PNG",
    layerIndex: 5,
  },
  {
    id: 18,
    name: "Madonna Blonde",
    variant: "Default",
    weight: 5,
    path: "Hair/MADONNA BLONDE.PNG",
    layerIndex: 5,
  },
  {
    id: 19,
    name: "Madonna Light Brown",
    variant: "Default",
    weight: 5,
    path: "Hair/MADONNA LIGHT BROWN.PNG",
    layerIndex: 5,
  },
  {
    id: 20,
    name: "Madonna Red",
    variant: "Default",
    weight: 5,
    path: "Hair/MADONNA RED.PNG",
    layerIndex: 5,
  },
  {
    id: 21,
    name: "Mamba Black",
    variant: "Default",
    weight: 5,
    path: "Hair/MAMBA BLACK.PNG",
    layerIndex: 5,
  },
  {
    id: 22,
    name: "Mamba Red",
    variant: "Default",
    weight: 5,
    path: "Hair/MAMBA RED.PNG",
    layerIndex: 5,
  },
  {
    id: 23,
    name: "Poofy Black",
    variant: "Default",
    weight: 11,
    path: "Hair/POOFY BLACK.PNG",
    layerIndex: 5,
  },
  {
    id: 24,
    name: "Poofy Blonde",
    variant: "Default",
    weight: 11,
    path: "Hair/POOFY BLONDE.PNG",
    layerIndex: 5,
  },
  {
    id: 25,
    name: "Poofy Brown",
    variant: "Default",
    weight: 11,
    path: "Hair/POOFY BROWN.PNG",
    layerIndex: 5,
  },
  {
    id: 26,
    name: "Pop Brown",
    variant: "Default",
    weight: 175,
    path: "Hair/POP HAIR BROWN.PNG",
    layerIndex: 5,
  },
  {
    id: 27,
    name: "Pop Red",
    variant: "Default",
    weight: 175,
    path: "Hair/POP HAIR RED.PNG",
    layerIndex: 5,
  },
  {
    id: 28,
    name: "Red Long Curly",
    variant: "Default",
    weight: 85,
    path: "Hair/RED LONG CURLY.PNG",
    layerIndex: 5,
  },
  {
    id: 29,
    name: "Scarface",
    variant: "Default",
    weight: 5,
    path: "Hair/SCARFACE HAIR.PNG",
    layerIndex: 5,
  },
  {
    id: 30,
    name: "Blonde Short Curly",
    variant: "Default",
    weight: 65,
    path: "Hair/SHORT CURRLY BLONDE.PNG",
    layerIndex: 5,
  },
  {
    id: 31,
    name: "Brown Short Curly",
    variant: "Default",
    weight: 65,
    path: "Hair/SHORT CURRLY BROWN.PNG",
    layerIndex: 5,
  },
  {
    id: 32,
    name: "Red Short Curly",
    variant: "Default",
    weight: 65,
    path: "Hair/SHORT CURRLY RED.PNG",
    layerIndex: 5,
  },
];
const AllHeadphoneElements = [
  {
    id: 0,
    name: "Headphones",
    variant: "Default",
    weight: 5,
    path: "Headphone/HEADPHONE3.PNG",
    layerIndex: 6,
  }, //none
  {
    id: 1,
    name: "None",
    variant: "Default",
    weight: 1158,
    path: "Headphone/NONE.PNG",
    layerIndex: 6,
  },
];

module.exports = {
  AllBackgroundElements,
  AllBaseElements,
  AllClothesElements,
  AllGlassesElements,
  AllHairElements,
  AllEyeElements,
  AllHeadphoneElements,
};
